### ISSUE TITLE
LiDAR data

### ISSUE THREAD

**Issue by nachovizzo** [UMich-CURLY/unified_cvo#1]
Great work!

Is there any plan to extend this for LiDAR only data?

**Comment by zeroAska** [comment]
Thanks for asking! We did have some code on Lidar data, though the parameters are not extensively tested or tuned yet. To compile with Lidar support, please set the [flag](https://github.com/UMich-CURLY/unified_cvo/blob/78317b1e9b4c82cb85207362f98f888338c6fcf1/CMakeLists.txt#L14) to be true in `CMakeLists.txt`.  The difference between LiDAR and image input is that the [FEATURE_DIMENSIONS](https://github.com/UMich-CURLY/unified_cvo/blob/78317b1e9b4c82cb85207362f98f888338c6fcf1/CMakeLists.txt#L502) is set to 1 instead of 5.  Example code that runs LiDAR frame-to-frame odometry can be found on:
* Geometric Registration: `src/experiments/main_cvo_gpu_lidar_raw_geometric.cpp`
* Intensity Registration: `src/experiments/main_cvo_gpu_lidar_raw_intensity.cpp`
* Semantic Registration: `src/experiments/main_cvo_gpu_lidar_raw_semantic.cpp`

A starting point to launch an experiment is `scripts/cvo_intensity_loam.bash` which we use LegoLoam's way of downsampling Lidar inputs from KITTI.  Another launch script example is  `scripts/cvo_geoemtric_range_ell.bash` where we select high gradient edge points from KITTI.

**Comment by nachovizzo** [comment]
Thanks for the fast reply! I will give it a look

**Comment by Rotatingpencil** [comment]
Hello, can you compile the unified_cvo in your environment or docker? I cannot compile in both of them @nachovizzo
